language: node_js
node_js:
  - 0.10
env:
  - NODE_ENV=test
services:
  - mongodb
before_install:
  - npm i -g grunt-cli
script:
  - grunt build
deploy:
  provider: heroku
  api_key: 6d224274-aa8c-4742-bfd0-f65baa4474a1
  app: freelookinfo
