language: node_js
node_js:
  - 0.12
env:
  - NODE_ENV=development

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm i -g gulp@3.8.11 bower
  - cd app && npm i && bower i

script:
  - gulp unit
  - gulp e2e:dist